# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.arch }}-${{ matrix.triplet_platform}}-ci
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]
        arch: [x86, x64, armv7a-nilrt]
        include:
          - os: windows-2022
            triplet_platform: windows-static
          - os: ubuntu-22.04
            triplet_platform: linux
        exclude:
        - os: ubuntu-22.04
          arch: x86
        - os: windows-2022
          arch: armv7a-nilrt
        
    steps:
    - name: Restore vcpkg cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/vcpkg_cache
        key: vcpkg-${{ matrix.arch }}-${{ matrix.triplet_platform}}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json', 'CMakePresets.json', 'shared-binary/**/CMakeLists.txt', 'vcpkg-overlay-ports/**/*.cmake', 'vcpkg-overlay-triplets/**/*.cmake') }}
        restore-keys: vcpkg-${{ matrix.arch }}-${{ matrix.triplet_platform}}

    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: lukka/get-cmake@latest
    - name: Install OS dependencies
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential g++ python3 zip unzip tar curl autoconf libudev-dev autoconf-archive automake libtool
    
    - name: Install NILRT armv7a Cross Compilation Tools
      if: ${{ matrix.arch == 'armv7a-nilrt' }}
      run: |
        sudo bash scripts/install-nilrt-armv7a-tools.sh

    - name: Setup VCPKG
      uses: lukka/run-vcpkg@v11

    - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
      uses: lukka/run-cmake@v10
      with:
          configurePreset: ci-${{ matrix.triplet_platform }}-${{ matrix.arch }}
          buildPreset: ci-${{ matrix.triplet_platform }}-${{ matrix.arch }}

    - name: Store Build Output Dependency Info
      uses: actions/upload-artifact@v4
      with:
        name: g_industrial_cam_${{ matrix.triplet_platform }}-${{ matrix.arch }}-share
        path: |
         ${{ github.workspace }}/build/vcpkg_installed/**/share

    - name: Store Build Output
      uses: actions/upload-artifact@v4
      with:
        name: g_industrial_cam_${{ env.VCPKG_DEFAULT_TRIPLET }}
        path: |
         ${{ github.workspace }}/LabVIEW/g_industrial_cam/bin
         ${{ github.workspace }}/build/vcpkg_installed/**/tools/aravis

    - name: Save vcpkg cache
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/vcpkg_cache
        key: vcpkg-${{ matrix.arch }}-${{ matrix.triplet_platform}}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json', 'CMakePresets.json', 'shared-binary/**/CMakeLists.txt', 'vcpkg-overlay-ports/**/*.cmake', 'vcpkg-overlay-triplets/**/*.cmake') }}
